[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
src_paths = ["src", "."]

[tool.mypy]
ignore_missing_imports = true

[tool.mypy.simplejson]
ignore_missing_imports = true
